### ISSUE TITLE
Question about chopper plugin

### ISSUE THREAD

**Issue by rgeneaux** [sq-lumin/pymodaq_plugins_tadetector-main#1]
Hi @sq-lumin!
This is more of a question than an issue.

I've started to try to implement a new camera+chopper to do TA so I looked at the way you did it in your plugin. I read the chopper status through a NI daq card so I tried with the daqmx plugin, which kind of works but is a bit weird (lots of messages in console, sometimes it says data rate is too fast). If you are also using a daq card to read the chopper status, would you be able to share your chopper plugin? 
Thanks!

**Comment by sq-lumin** [comment]
Hi @rgeneaux !
Thank you for your question, I'm also using an NI daq card to read my chopper, and I remember dealing lots of weird errors in the console as well, mainly about buffer size (somehow it was complaining about reading too _few_ samples). 

You can find the plugin (0D viewer) here:
https://github.com/sq-lumin/pymodaq_plugins_chopper

It is pretty much a copy/paste of an existing daqmx plugin, with a few tweaks, like this one for the buffer issues:
```python 
from ctypes import c_ulong

...

#set the proper buffer size manually. Not needed if Nsamples is big enough (>=50), but needed for smaller Nsamples.
self.controller['chopper']._task.SetBufInputBufSize(c_ulong(self.settings.child('chopper_params').child('Nsamples').value()))
```

I can't remember if I encountered an error about data rate specifically but I hope this will at least give you some inspiration.
I will close this issue here but feel free to open a new one on the other repo if you have any question !

Best of luck with your plugin !
